// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RMS.DataAccess.Data;

#nullable disable

namespace RMS.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240425071727_addLastConsumptionReport")]
    partial class addLastConsumptionReport
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RMS.Models.GoodsReceiptOverview", b =>
                {
                    b.Property<int>("RequestNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RequestNo"));

                    b.Property<string>("GoodReceipt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OBDNo")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("OBD No");

                    b.Property<string>("QuotationNo")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Quotation No");

                    b.Property<string>("SalesNo")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("Sales No");

                    b.HasKey("RequestNo");

                    b.ToTable("GoodsReceiptOverview");
                });

            modelBuilder.Entity("RMS.Models.InventoryUpdateOverview", b =>
                {
                    b.Property<string>("ProductCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Consumption")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Product Code");

                    b.Property<int>("OpenStock")
                        .HasColumnType("int");

                    b.Property<string>("Plant")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Uom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductCode");

                    b.ToTable("InventoryUpdateOverviews");
                });

            modelBuilder.Entity("RMS.Models.LastConsumptionReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("DateConsumed")
                        .HasColumnType("date");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MedicineName")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Medicine Name");

                    b.Property<int>("QuantityConsumed")
                        .HasColumnType("int")
                        .HasColumnName("Quantity Consumed");

                    b.HasKey("Id");

                    b.ToTable("LastConsumptionReports");
                });

            modelBuilder.Entity("RMS.Models.OpenGoodsReceipts", b =>
                {
                    b.Property<int>("ReceiptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReceiptId"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("MaterialName")
                        .IsRequired()
                        .HasColumnType("varchar(40)")
                        .HasColumnName("Material Name");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Supplier")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("TotalPrice")
                        .HasColumnType("float");

                    b.Property<double>("UnitPrice")
                        .HasColumnType("float");

                    b.HasKey("ReceiptId");

                    b.ToTable("OpenGoodsReceipts");
                });

            modelBuilder.Entity("RMS.Models.OpenInvoiceConfirmation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Customer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("InvoiceId")
                        .IsRequired()
                        .HasColumnType("varchar(30)")
                        .HasColumnName("Invoice Id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("TotalAmount")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("OpenInvoiceConfirmations");
                });

            modelBuilder.Entity("RMS.Models.OpenRequestReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("varchar(30)")
                        .HasColumnName("Product Name");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<double>("TotalValue")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("OpenRequestReports");
                });

            modelBuilder.Entity("RMS.Models.QuotationApproval", b =>
                {
                    b.Property<int>("RequestNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RequestNo"));

                    b.Property<string>("Quotation")
                        .HasColumnType("varchar(20)")
                        .HasColumnName("Quotation No");

                    b.Property<double>("TotalAmount")
                        .HasColumnType("float");

                    b.HasKey("RequestNo");

                    b.ToTable("QuotationApprovals");
                });
#pragma warning restore 612, 618
        }
    }
}
